---
- name: Partition the data disk
  shell: 'echo "n\np\n1\n\n+150M\nn\np\n2\n\n\nt\n2\n8e\nw" | fdisk {{ block_device }}'
  when: "not ansible_devices.{{ block_device.split('/')[2] }}.partitions"

- name: Install LVM and DRBD
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - lvm2
    - drbd8-utils

- name: Setup the LVM Volume Group
  lvg:
    vg: data
    pvs: "{{ block_device }}2"
    vg_options: ''

- name: Setup the LVM Logical Volume
  lvol:
    vg: data
    lv: "{{ group_names[0] }}"
    size: 100%VG

- name: Format the Logical Volume
  filesystem:
    fstype: ext4
    dev: "/dev/data/{{ group_names[0] }}"

- name: Configure DRBD
  template:
    src: ../templates/drbd.j2
    dest: /etc/drbd.conf
    owner: root
    group: root
    mode: 0644

- name: Install the drbd module
  modprobe:
    name: drbd
    state: present

- name: Is DRBD initialized?
  shell: "drbdmeta /dev/drbd0 v06 0 dstate"
  register: configured
  failed_when: "255 != configured.rc and 20 != configured.rc"
  changed_when: False

- name: Zero-out the head of the metadata partition if needed
  shell: "dd if=/dev/zero of={{ block_device }}1 bs=1M count=128"
  when: "255 == configured.rc"

- name: Initialize the DRBD metadata if needed
  shell: "echo yes | drbdadm create-md {{ group_names[0] }}"
  when: "255 == configured.rc"
  notify: 
    - restart heartbeat

- name: Start DRBD service
  service:
    name: drbd
    state: restarted
    sleep: 10

- name: Invalidate DRBD on secondary node
  shell: "drbdadm invalidate {{ group_names[0] }}"
  when: "primary is not defined"
  register: invalidated
  # Don't fail on 'already syncing invalidation error'
  failed_when: "11 != invalidated.rc and 0 != invalidated.rc" 
  changed_when: "11 != invalidated.rc"
  notify: 
    - restart heartbeat
    - restart drbd

- name: Set DRBD primary
  shell: "drbdadm primary {{ group_names[0] }}"
  when: "primary is defined"
  register: primaryset
  failed_when: "11 != primaryset.rc and 0 != primaryset.rc"
  changed_when: "0 != primaryset.rc"
  notify: 
    - restart heartbeat
    - restart drbd

- name: Configure Heartbeat Resources
  template:
    src: hb_haresources.j2
    dest: /etc/heartbeat/haresources
    owner: root
    group: root
    mode: 0640
  notify: restart heartbeat
